# Generated by Django 4.2.3 on 2023-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dondesang', '0003_remove_entretien_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='date_de_p',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
