# Generated by Django 4.2.3 on 2023-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dondesang', '0004_alter_entretien_date_de_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='apte',
            field=models.CharField(blank=True, choices=[('APTE', 'APTE'), ('INAPTE TEMPORAIRE', 'INAPTE TEMPORAIRE'), ('INAPTE DEFINITIVE', 'INAPTE DEFINITIVE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='code_ci',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='identification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
