# Generated by Django 4.2.3 on 2023-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dondesang', '0005_entretien_apte_entretien_code_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='date_de_p',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
