# Generated by Django 4.2.3 on 2023-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dondesang', '0006_alter_entretien_date_de_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='collects',
            field=models.ManyToManyField(blank=True, to='dondesang.collects'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='donneur',
            field=models.ManyToManyField(blank=True, to='dondesang.donneur'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='n_partenaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='poid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='ta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='taux_hd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
