# Generated by Django 4.2.3 on 2023-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dondesang', '0007_alter_donneur_collects_alter_donneur_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predon',
            name='code_ci',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
